# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_title', models.CharField(max_length=150)),
                ('Task_info', models.CharField(max_length=150)),
            ],
        ),
    ]
