# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('instance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_title', models.CharField(max_length=150)),
                ('Task_info', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TaskIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='gentask',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.TaskIcon'),
        ),
        migrations.AddField(
            model_name='gentask',
            name='taskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Task'),
        ),
        migrations.AddField(
            model_name='gentask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
