# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20170516_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gentask',
            name='file',
            field=models.FilePathField(blank=True, null=True, path='D:\\agat_new\\agat_web\\agatweb\\static'),
        ),
    ]
