# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20170516_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gentask',
            name='file',
        ),
    ]
